---
# tasks file for common
- name: install common packages
  become: true
  package:
    name:
    - httpd
    - nodejs
    - npm
    state: present


- name: start httpd service
  become: true
  service:
    name: httpd
    state: started
    enabled: true 

- name: Copy source code
  become: true
  synchronize:
    src: "{{ playbooks_dir }}/../../"
    dest: "/opt/todo"
    mode: push
    recursive: true
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=.github"
      - "--exclude=ansible"

- debug:
    var: playbook_dir
