---
# tasks file for common
- name: install common packages
  become: true
  package:
    name:
    - httpd
    - nodejs
    - npm
    state: present


- name: start httpd service
  become: true
  service:
    name: httpd
    state: started
    enabled: true 

- name: copy source code 
  become: true
  synchronize:
    src: "{{ playbook_dir }}/../../../../../../"
    dest: "/opt/todo-app"
    delete: true
    recursive: true
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=.github"
      - "--exclude=ansible"