---
# tasks file for backend

- name: Install backend packages using npm install
  become: true
  command: npm install
  args:
    chdir: /opt/todo/todo-backend


- name: install PM2 globally
  become: true
  npm:
    name: pm2
    global: true
    state: present

- name: check if start.js is there
  stat:
   path: /opt/todo/todo-backend/start.js
  register: start_js


- name: debugging start.js
  debug:
    msg: "start.js exists: {{ start_js.stat.exists }}"

- name: check the name to list
  become: true
  command: pm2 list
  register: pm2_list
  changed_when: false

- name: Debug the PM2 list
  debug:
    var: pm2_list.stdout_lines

- name: Start the backend application with PM2
  become: true
  command: "pm2 start -f start.js"
  args:
    chdir: /opt/todo/todo-backend
  when: start_js.stat.exists

- name: set pm2 to start on boot
  become: true
  command: pm2 startup
  args:
    chdir: /opt/todo/todo-backend